export const FILLNODE_SET_USER = 'FILLNODE_SET_USER';
export const FILLNODE_RESET = 'FILLNODE_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
